version: "3.9"

services:
    app:
        container_name: iris
        image: terminal
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT}:${PORT}"